pub const CARD_DATA: &[(&str, &str)] = &[
    // Greetings & Basics
    ("Bore da", "Good morning"),
    ("Prynhawn da", "Good afternoon"),
    ("Nos da", "Good night"),
    ("Sut mae? / Shwmae?", "How are you?"),
    ("Croeso", "Welcome"),
    ("Iawn, diolch", "Fine, thank you / OK, thanks"),
    ("Pob lwc", "Good luck"),
    ("Hwyl fawr", "Goodbye / Bye"),
    ("Os gwelwch yn dda", "Please"),
    ("Diolch", "Thank you / Thanks"),
    ("Dim diolch", "No thank you"),
    ("Iechyd da!", "Cheers!"),
    ("Esgusodwch fi", "Excuse me"),
    ("Mae'n ddrwg gen i", "I'm sorry"),
    ("Wyt ti'n siarad Saesneg?", "Do you speak English?"),
    ("Ydw", "Yes"),
    ("Nac ydw", "No"),
    ("Beth yw dy enw di?", "What is your name?"),
    ("Fy enw i yw...", "My name is..."),
    ("Ble mae'r tŷ bach?", "Where is the toilet? / Where's the loo?"),

    // Getting Around
    ("Bws", "Bus"),
    ("Trên", "Train"),
    ("Tacsi", "Taxi"),
    ("Maes awyr", "Airport"),
    ("Gorsaf", "Station"),
    ("Tocyn", "Ticket"),
    ("Ble mae'r orsaf drên?", "Where is the train station?"),
    ("I'r chwith", "To the left"),
    ("I'r dde", "To the right"),
    ("Yn syth ymlaen", "Straight ahead"),
    ("Map", "Map"),
    ("Ffordd", "Road"),
    ("Traeth", "Beach"),
    ("Mynydd", "Mountain"),
    ("Afon", "River"),
    ("Castell", "Castle"),
    ("Canol y dref", "Town centre"),

    // Accommodation
    ("Gwesty", "Hotel"),
    ("Ystafell", "Room"),
    ("Allwedd", "Key"),
    ("Archeb", "Booking"),
    ("Oes gennych chi ystafell wag?", "Do you have a vacant room?"),

    // Food & Drink
    ("Bwyd", "Food"),
    ("Diod", "Drink"),
    ("Brecwast", "Breakfast"),
    ("Cinio", "Lunch"),
    ("Swper", "Dinner"),
    ("Bwyty", "Restaurant"),
    ("Tafarn", "Pub"),
    ("Caffi", "Cafe"),
    ("Dŵr", "Water"),
    ("Cwrw", "Beer"),
    ("Gwin", "Wine"),
    ("Coffi", "Coffee"),
    ("Te", "Tea"),
    ("Bara", "Bread"),
    ("Caws", "Cheese"),
    ("Cig", "Meat"),
    ("Pysgod", "Fish"),
    ("Ga i'r bil, os gwelwch yn dda?", "Can I have the bill, please? / The bill, please"),
    ("Blasus iawn", "Very tasty"),
    ("Llefrith", "Milk"),
    ("Siwgr", "Sugar"),
    ("Mwynhewch eich pryd", "Enjoy your meal"),

    // Shopping
    ("Siop", "Shop"),
    ("Arian", "Money"),
    ("Faint mae'n ei gostio?", "How much does it cost?"),
    ("Cardyn credyd", "Credit card"),
    ("Agored", "Open"),
    ("Ar gau", "Closed"),

    // Numbers
    ("Un", "One"),
    ("Dau", "Two"),
    ("Tri", "Three"),
    ("Pedwar", "Four"),
    ("Pump", "Five"),
    ("Chwech", "Six"),
    ("Saith", "Seven"),
    ("Wyth", "Eight"),
    ("Naw", "Nine"),
    ("Deg", "Ten"),

    // Days of the Week
    ("Dydd Llun", "Monday"),
    ("Dydd Mawrth", "Tuesday"),
    ("Dydd Mercher", "Wednesday"),
    ("Dydd Iau", "Thursday"),
    ("Dydd Gwener", "Friday"),
    ("Dydd Sadwrn", "Saturday"),
    ("Dydd Sul", "Sunday"),

    // Emergencies
    ("Help!", "Help!"),
    ("Heddlu", "Police"),
    ("Ambiwlans", "Ambulance"),
    ("Ysbyty", "Hospital"),
    ("Meddyg", "Doctor"),
    ("Mae angen help arna i", "I need help"),

    // Common Phrases & Questions
    ("Pryd?", "When?"),
    ("Pam?", "Why?"),
    ("Pwy?", "Who?"),
    ("Beth?", "What?"),
    ("Sut?", "How?"),
    ("Ble?", "Where?"),
    ("Dwi ddim yn deall", "I don't understand"),
    ("Arafach, os gwelwch yn dda", "Slower, please"),
    ("Ailadroddwch, os gwelwch yn dda", "Repeat, please"),
    ("Am faint o'r gloch?", "At what time?"),
    ("Heddiw", "Today"),
    ("Yfory", "Tomorrow"),
    ("Ddoe", "Yesterday"),
    ("Nawr", "Now"),
    ("Yn ddiweddarach", "Later"),
    ("Dim problem", "No problem"),
    ("Gwych!", "Great!"),
];
